[pytest]
addopts = --strict-markers -n 4 --reruns 3 --cov=qnexus --cov-report=term --doctest-modules
norecursedirs = tests/data
markers =
    create: marks tests as those that have side effects involving resource creation (deselect with '-m "not create"')
